### ISSUE TITLE
Suggestion: Project Sandcastle integration

### ISSUE THREAD

**Issue by ghost** [raspberryenvoie/odysseyn1x#1]
I don’t know how hard this might be, but it would be cool if there would be Project Sandcastle Linux and Android integration. This is just a suggestion, but it would be really cool and pretty helpful. The user would have to use checkra1n to boot into pongoOS and then run a ./load-linux script that was compiled using gcc for example. I’ll do more testing to see if this might work.

**Comment by raspberryenvoie** [comment]
Hello, it would be great aye. I think it might work, I'm looking into it. Let me know what you find out after your tests.

**Comment by raspberryenvoie** [comment]
I'm working on it. Let me know if you'd like to try the beta and tell me if you find a bug.

**Comment by raspberryenvoie** [comment]
Thanks for the idea, the latest release includes it. Download it [here](https://github.com/raspberryenvoie/odysseyn1x/releases).

**Comment by ghost** [comment]
Thank you so much! I forgot to do the tests xD, but I figured it might work out.

**Comment by MyCatCondo** [comment]
Oh and also can you also support Linux Project Sandcastle? It should be similar, you just plug in a iDevice, put it in DFU, and run ./load-linux with the Linux.lzma package. It’s a little easier than Android Projct Sandcastle, so I hope you can do this too. Thanks!

**Comment by raspberryenvoie** [comment]
Np!
