### ISSUE TITLE
Can't ssh into the device, after installing oddyseyra1n.

### ISSUE THREAD

**Issue by superrnovae** [raspberryenvoie/odysseyn1x#10]
Default password alpine doesn't seem to work anymore. 
Do i have to use another port? Device isn't connected to any wireless networks.
Also, I am unable to use sliver as it fails due to wrong password.

**Device:** iPad Air 2 (WiFi)
**OS:** iPad OS 14.0.1

**Comment by raspberryenvoie** [comment]
Hello,
For checkra1n the port is 44. For odysseyra1n it’s port 22 or 2222.
The password is `alpine`.
You could try that.

**Comment by ghost** [comment]
Wait wasn’t this a fix in #3?

**Comment by raspberryenvoie** [comment]
@MyCatCondo I think he can't ssh into his device. It's not related to the installation of Project Sandcastle.

**Comment by raspberryenvoie** [comment]
@MyCatCondo I think @bakedpotato191 can't ssh into his device. It's not related to the installation of Project Sandcastle.

**Comment by ghost** [comment]
@raspberryenvoie then maybe @bakedpotato191 can try installing the OpenSSH package in Cydia or Sileo

**Comment by Anwu949** [comment]
I use the same device as Mr. BakedPotato. iPad Air 2(Ios 14.1). It has the same issue. From my experience, after you use Odysseyra1n, and you try to start download Project Sandcastle, it asks for the root password. Alpine no longer works.

**Comment by raspberryenvoie** [comment]
That's weird. This issue has been fixed since v2.2. Make sure to answer that you're using odysseyra1n when setting up Project Sandcastle.

**Comment by MyCatCondo** [comment]
That is really weird.

**Comment by 34G3R** [comment]
hi has anyone actually found a fix ? i cant ssh to remove this odyssey shizz! i done it on hello screen now i cant access my phone as i cant bypass because it wont connect through ssh, it says denied password changed.. dosnt matter what app i try ssh with. please help me , i just wanted isleo now i wish i never tried -.- i dont wanna restore with itunes else i have to update.. i followed the odysseyra1n guid on google, surely theres a reverse ? or a secrect password ? some rsa fingerpring thing shows each time but it dosnt help... ANYONE HELP PLEASE ILL DONO IF I HAVE TO 
<img width="258" alt="Capture" src="https://user-images.githubusercontent.com/74840505/99889593-8eba1b80-2cbb-11eb-9d3c-f12c516dc26f.PNG">

**Comment by raspberryenvoie** [comment]
Hi, which command did you type to connect through ssh?

**Comment by 34G3R** [comment]
i been trying apps as putty refuses me , but on the apps i just choose ssh 127.0.0.1 port 22 username root password alpine but it refuses it , iv tried 22, 44, 2222, 4444, do you have discord or something so you can help me ? im probably just stupid tbh XD or just type and ill try... i been up for hours trying litterally any help is good at this stage

**Comment by 3xtc** [comment]
everytime i try new ssh terminal app or anything it says to add rsa fingerprint host (if i do or dont same result) i dont wanna update fml

**Comment by 34G3R** [comment]
please help me bro still nothing -.-

**Comment by raspberryenvoie** [comment]
I'm not going to help you bypassing you iPhone because as you know it, it's illegal, and I don't know how to do it.

However I can help you to connect through ssh to your iPhone:
1. As you're using Windows, you'll need to download and flash odysseyn1x onto a usb drive
2. Boot it
3. Select `Shell`
4. Type `iproxy 2222 22 > /dev/null 2>&1 &` and hit enter.
5. Now connect through ssh with `ssh -p2222 root@127.0.0.1` and press enter.

**Comment by ThisIsSheikhRidwan** [comment]
**### I am also having the same problem**
I am opening SSH With 3UTools
But as I am understanding the password got changed.

i am writing down the proccess how i used it.  ( i was using a bypassed iphone 7)
first i removed the checkra1n from iphone system then my iphone came to the hello screen and then i booted in the app by usb....jailbreaked with Checkra1n first......then without bypassing or installing cydia....i have installed the odysseyra1n
and then booted in windows again and then open Ifrpfile to bypass .........at that time when ifrpfile.exe file got opened ....an error shown permission denied (password)
then i opened 3Utools....opened SSH tunnel from there....and i just understood  that password got changed...please tell me how can i fix this problem...thank you

i am attaching the picture 
![snap38](https://user-images.githubusercontent.com/75214032/100546975-797e5780-328e-11eb-88be-d4ad685d5e6a.png)

**Comment by ThisIsSheikhRidwan** [comment]
i have no way to access my iphone before bypassing to change the root password from iphone.....just need to change it from computer or somehow anywhere else....i am seeking for the help.....please let me know what to do now....

i am not asking for help to bypass....but let me know how the password got changed what is the present password....as i can get the access to ssh....

**Comment by ThisIsSheikhRidwan** [comment]
also please note default password alpine is not working ....seeking for an solution please help

**Comment by ThisIsSheikhRidwan** [comment]
phone can be jailbroken everytime but doesn't gets access to the ssh....i hope all the information helps you to understand the problem

FOLLOWING

**Comment by ThisIsSheikhRidwan** [comment]
Hello @bakedpotato191 & @raspberryenvoie I have found the solution of it

Step 1 Open 3UTools and download the latest firmware which can be bypassed by checkra1n (i have downloaded 14.2 for that)
Note: It Should be a verified or signed ipsw ios file. which can be checked by SHSH

Then Use Easy Flash in 3UTOOLS With Retain User Data

after flashing jailbreak with checkra1n

and then bypass your phone with IFRPFILE

You can see SSH got connected

then bypass

Let Me Know If it works.....

I can assure you 14.2 can be bypassed easily. you can update with your all important files from 3UTOOLS.

**Comment by superrnovae** [comment]
@ThisIsSheikhRidwan I've never had issues on vanilla checkra1n. My issue is with odysseyra1n where I can't ssh into the device, no matter whether I transition after bypassing of before. 
My guess is, either the device is incompatible or something fails, although the process succeeds according to the cli output.

**Comment by superrnovae** [comment]
My guess would be is that the password somehow gets corrupted during the process. 
I've seen this happen when flashing router firmware, tomato in my case, where the password would get corrupted to something unreadable.

**Comment by ThisIsSheikhRidwan** [comment]
Exactly Somehow password gets corrupted...
and then SSH Tunnel Doesn't connects anymore

**Comment by raspberryenvoie** [comment]
When you install odysseyra1n the password is somehow changed but it doesn't happen with vanilla checkra1n, that's weird. I'm happy you found a solution @ThisIsSheikhRidwan! My help wasn't very useful.

**Comment by caspaas** [comment]
so someone has a better solution then ? because its sucks that odyssey is having this problem.

Getting this with multiple Iphones now.
Password just get corrupted and fails.

**Comment by 34G3R** [comment]
iknow fix

**Comment by caspaas** [comment]
> 
> 
> iknow fix

do tell? please ? xD

**Comment by cikeZ00** [comment]
So, the built in SSH server fails to authenticate.

****However****, by installing openssh and switching the port to something like "1111"  I was able to gain SSH access on said port using the password "alpine".
![Djjx4FVD 1](https://user-images.githubusercontent.com/17727672/103450395-ffd6f080-4cb5-11eb-8a67-e0ec9e4ae5d3.png)

**Comment by caspaas** [comment]
> 
> 
> So, the built in SSH server fails to authenticate.
> 
> ****However****, by installing openssh and switching the port to something like "1111" I was able to gain SSH access on said port using the password "alpine".
> ![Djjx4FVD 1](https://user-images.githubusercontent.com/17727672/103450395-ffd6f080-4cb5-11eb-8a67-e0ec9e4ae5d3.png)

you are a legend thank you <3

**Comment by raspberryenvoie** [comment]
@bakedpotato191 Have you tried the above workaround? If it works fell free to close this issue.

**Comment by superrnovae** [comment]
> 
> 
> @bakedpotato191 Have you tried the above workaround? If it works fell free to close this issue.

I can't, unfortunately, since my iPad is iCloud bypassed, I am unable to install openssh via cydia.

Edit: but if the above worked for @cikeZ00 and @caspaas I guess we can mark that as a solution and close the issue.

**Comment by raspberryenvoie** [comment]
> > @bakedpotato191 Have you tried the above workaround? If it works fell free to close this issue.
> 
> I can't, unfortunately, since my iPad is iCloud bypassed, I am unable to install openssh via cydia.
> 
> Edit: but if the above worked for @cikeZ00 and @caspaas I guess we can mark that as a solution and close the issue.

As you want

**Comment by superrnovae** [comment]
> 
> 
> So, the built in SSH server fails to authenticate.
> 
> ****However****, by installing openssh and switching the port to something like "1111" I was able to gain SSH access on said port using the password "alpine".
> ![Djjx4FVD 1](https://user-images.githubusercontent.com/17727672/103450395-ffd6f080-4cb5-11eb-8a67-e0ec9e4ae5d3.png)
