### ISSUE TITLE
ACPI Error

### ISSUE THREAD

**Issue by DEALWITHIT199** [raspberryenvoie/odysseyn1x#11]
ok. so everytime I boot to Odysseyn1x the verbose boot thingy shows an error "ACPI Error". can anyone tell me how to fix this error?  Ty in advanced!

**Comment by raspberryenvoie** [comment]
Hello, which version of odysseyn1x are you using?

**Comment by DEALWITHIT199** [comment]
v2.5

**Comment by DEALWITHIT199** [comment]
> Hello, which version of odysseyn1x are you using?

I used v2.5 the latest.

**Comment by raspberryenvoie** [comment]
I know it isn't a solution but you could try on another pc.
Otherwise, try v1 https://github.com/raspberryenvoie/odysseyn1x/releases/tag/v1
It ships with a different kernel, let me know if it boots.

**Comment by DEALWITHIT199** [comment]
Thanks for the reason but v1 checkra1n is 0.10.2 and my iOS version is 14.0.

**Comment by raspberryenvoie** [comment]
Try with another pc then. May I know the specs of your pc please?

**Comment by DEALWITHIT199** [comment]
> Try with another pc then. May I know the specs of your pc please?

My pc specs:
Manufacturer: HP
Model: HP Laptop 15-db0xxx
Processor: AMD A6-9225 RADEON R4, 5 COMPUTE CORES 2C+3G 2.60GHz
RAM: 4.00GB
System Type: 64bit Operating System, x64-based processor

**Comment by raspberryenvoie** [comment]
Is your Bios up to date?

**Comment by MyCatCondo** [comment]
I receive the ACPI error too, with a Dell Latitude D530 and after it throws a few errors it stops throwing errors. It’s nothing to worry about 😉

**Comment by DEALWITHIT199** [comment]
> Is your Bios up to date?

Yes my BIOS is up to date.

**Comment by raspberryenvoie** [comment]
@DEALWITHIT199 Can you boot odysseyn1x even with this ACPI error?

**Comment by DEALWITHIT199** [comment]
> @DEALWITHIT199 Can you boot odysseyn1x even with this ACPI error?

Similar to MyCatCondo. I boot to Odysseyn1x then it shows ACPI Error then it stops throwing errors then the booting continues to Odysseyn1x menu. I try to jailbreak using checkra1n and it was successful but I'm still worried about the ACPI Error.

**Comment by MyCatCondo** [comment]
> I try to jailbreak using checkra1n and it was successful but I'm still worried about the ACPI Error.
>
The ACPI error is just a annoying bug. I get an ACPI error on a lot of my devices running Linux and ignoring it is fine. Here, you can see https://www.linuxquestions.org/questions/linux-hardware-18/acpi-error-what-means-4175605357/#post5706962 for a little reference. (Sorry, the hyperlink did not want to work.) It says that the ACPI may be faulty, but the error can be ignored.

**Comment by raspberryenvoie** [comment]
@MyCatCondo is right. If you're able to boot odysseyn1x,you can just ignore this message. If you want more info, just check the link above. Feel free to close the issue if you want to.
Have a nice day @MyCatCondo and @DEALWITHIT199 :)

**Comment by MyCatCondo** [comment]
You too @raspberryenvoie 
You might want to close the issue btw

**Comment by raspberryenvoie** [comment]
Closing this issue

**Comment by DEALWITHIT199** [comment]
Thank you for helping guys!
