### ISSUE TITLE
Grub error

### ISSUE THREAD

**Issue by DTX3** [raspberryenvoie/odysseyn1x#12]
I get a grub error when trying to boot from my USB drive. See screenshot

![IMG-4800](https://user-images.githubusercontent.com/59918994/97197263-57804980-17a5-11eb-8fe3-10854778753d.jpg)

**Comment by raspberryenvoie** [comment]
Hi, download and flash the iso again using balenaEtcher

**Comment by DTX3** [comment]
Thanks that resolved my issue using BalenaEtcher.

I was using Rufus to add the iso image intially.

**Comment by starcapri** [comment]
> Thanks that resolved my issue using BalenaEtcher.
> 
> I was using Rufus to add the iso image intially.

I'm also getting the same error and yea I also used Rufus to Flash i will try with balena later.

**Comment by ghost** [comment]
Rufus for some reason provides an error
