### ISSUE TITLE
Jb

### ISSUE THREAD

**Issue by vnnaonymous** [raspberryenvoie/odysseyn1x#13]

**Comment by raspberryenvoie** [comment]
Hi, could you provide more information?

**Comment by ghost** [comment]
There isn’t a description, so I don’t know what you’re asking. Can you give me more information?

**Comment by ghost** [comment]
If @vnnaonymous is wondering how to jailbreak his iDevice, a guide is on the homepage of this GitHub project [here](https://github.com/raspberryenvoie/odysseyn1x/). I hope this helps!

**Comment by raspberryenvoie** [comment]
I'm closing this issue no further info has been provided since Oct 27th
