### ISSUE TITLE
in Grub rescue dont know what else to do

### ISSUE THREAD

**Issue by DreadWolf-sketch** [raspberryenvoie/odysseyn1x#16]
says unkown file system then enters grub rescue

**Comment by raspberryenvoie** [comment]
Hi, download and flash the iso again using balenaEtcher please. Rufus doesn't work well with odysseyn1x

**Comment by DreadWolf-sketch** [comment]
> Hi, download and flash the iso again using balenaEtcher please. Rufus doesn't work well with odysseyn1x

Didnt need to use balenaEtcher, got it to work by switching from MBR partition to GPT, And swapping to DD image mode instead of ISO image mode

**Comment by raspberryenvoie** [comment]
Great, feel free to close this issue is your it is solved.
Btw I'm will add your workaround to the readme.

**Comment by ghost** [comment]
So that’s how you get Rufus to work. Lol
