### ISSUE TITLE
I am getting this issue trying to boot to usb device

### ISSUE THREAD

**Issue by RickyHunter024** [raspberryenvoie/odysseyn1x#18]
![image](https://user-images.githubusercontent.com/38816578/101888157-75174000-3ba6-11eb-881b-e05126b593c9.jpeg)

**Comment by raspberryenvoie** [comment]
Are you still able to boot?

**Comment by RickyHunter024** [comment]
I waited like 20/30 minutes and it's stuck at this so I just force shut down

**Comment by raspberryenvoie** [comment]
#6

**Comment by RickyHunter024** [comment]
It worked now I had to install the iso file again because it was corrupted

**Comment by raspberryenvoie** [comment]
So you're getting the same problem as #6. Try updating your Bios if it isn't up to date.

**Comment by raspberryenvoie** [comment]
Great! So I'm closing this issue

**Comment by RickyHunter024** [comment]
Sry for wasting your time

**Comment by RickyHunter024** [comment]
Just another question is there an option to ssh?

**Comment by raspberryenvoie** [comment]
You can do it yourself throught command line select shell, run iproxy then run ssh. I'll add an option in a future release

**Comment by RickyHunter024** [comment]
Ok thanks!!

**Comment by raspberryenvoie** [comment]
np

**Comment by ghost** [comment]
I thought it would be helpful to mention that the ACPI errors are usually nothing to worry about. :)

**Comment by raspberryenvoie** [comment]
I believe those errors are from caused by the manufacturer's badly implemented BIOS.

**Comment by raspberryenvoie** [comment]
> Just another question is there an option to ssh?

[v2.9](https://github.com/raspberryenvoie/odysseyn1x/releases/tag/v2.9) adds an option to do that.
