### ISSUE TITLE
Update checkra1n to 0.12.2

### ISSUE THREAD

**Issue by ghost** [raspberryenvoie/odysseyn1x#19]
Just thought I would put a reminder here :)
https://checkra.in/releases/0.12.2-beta

**Comment by raspberryenvoie** [comment]
Thank you :) I'll update it tomorrow

**Comment by raspberryenvoie** [comment]
I've just released [v2.9](https://github.com/raspberryenvoie/odysseyn1x/releases/tag/v2.9)
