### ISSUE TITLE
Project Sandcastle Linux Integration

### ISSUE THREAD

**Issue by ghost** [raspberryenvoie/odysseyn1x#2]
There are two kinds of Project Sandcastle, one of them is Android (thank you for integrating) and the second kind is Linux. I hope you can add Project Sandcastle Linux integration too. That would also be really cool, because then people can also install Linux on their iDevices. It’s similar to Android Project Sandcastle. I just hope you can add Linux Sandcastle support too. Thanks!

**Comment by raspberryenvoie** [comment]
Thanks again for the idea :)
I integrated it in the latest release: https://github.com/raspberryenvoie/odysseyn1x/releases

**Comment by ghost** [comment]
lol np! Also project sandcastle works on iPhone and also (I think) iPad too! That’s pretty cool!
