### ISSUE TITLE
Checkra1n blocked for more then 120 seconds

### ISSUE THREAD

**Issue by TomerGamerTV** [raspberryenvoie/odysseyn1x#20]
![image](https://user-images.githubusercontent.com/44266242/103526415-90195f00-4e89-11eb-9c73-58f62f3f7f23.jpeg)

iPad Air
ios 12.5

**Comment by raspberryenvoie** [comment]
Try to unplug and replug quickly the iPad as shown is [this video](https://www.youtube.com/watch?v=Rc0uP1t-RiE). Hope this help :)

**Comment by TomerGamerTV** [comment]
> Try to unplug and replug quickly the iPad as shown is [this video](https://www.youtube.com/watch?v=Rc0uP1t-RiE). Hope this help :)

I will try it but you know why it's happening?

**Comment by raspberryenvoie** [comment]
It's a known checkra1n bug, it's documented [here](https://github.com/checkra1n/BugTracker/issues/984)

**Comment by TomerGamerTV** [comment]
Can you add an option to restart the program is it's failed?

**Comment by TomerGamerTV** [comment]
> Try to unplug and replug quickly the iPad as shown is [this video](https://www.youtube.com/watch?v=Rc0uP1t-RiE). Hope this help :)

![image](https://user-images.githubusercontent.com/44266242/103592206-1326cd80-4efb-11eb-82b5-a1e89e71fbc7.jpeg)

Still not working

**Comment by raspberryenvoie** [comment]
Does your iPad Air have an A7 chip?  If it's the case, try to jailbreak your iPhone with [this version of odysseyn1x](https://github.com/raspberryenvoie/odysseyn1x/releases/tag/v2.4-checkra1n-0.10.1) and when checkra1n is stuck quickly plug/unplug it as said in my above message.

**Comment by TomerGamerTV** [comment]
Still not working

**Comment by raspberryenvoie** [comment]
I don't know then, have a look at the [checkra1n bugtracker](https://github.com/checkra1n/BugTracker) for more details. You can close this issue, if you want, as it's a checkra1n bug.
Have a nice day :)

**Comment by raspberryenvoie** [comment]
I'm closing this issue since it's a checkra1n bug. There is a new checkra1n version that you can try it. I hope you'll be able to jailbreak you iPad Air successfully!
