### ISSUE TITLE
cant install odyssey

### ISSUE THREAD

**Issue by SonThanhVN** [raspberryenvoie/odysseyn1x#21]
i have jailbreak my phone and then i choose odysseyra1n option when i click enter it start for a bit and have an error message say "broken pipe"

**Comment by SonThanh2k5** [comment]
![Uploading 1AE42528-EC36-4B0C-9D7A-77304B223E68.jpeg…]()

**Comment by SonThanhVN** [comment]
![Uploading 9A78867F-252C-4469-B599-808E70FE150E.jpeg…]()

**Comment by raspberryenvoie** [comment]
Try to unplug then replug the cable

**Comment by raspberryenvoie** [comment]
Is your problem solved? I am closing this issue because there have been no new messages since February. Don't hesitate to reopen it if you need help!
