### ISSUE TITLE
Can't install Sileo and Bootstrap

### ISSUE THREAD

**Issue by Yuki-dev-JP** [raspberryenvoie/odysseyn1x#24]
I use odysseyn1x, but it can't install Sileo and Bootstrap. 
error code: bash: zsh: command not found
Failed to install Procursus bootstrap and Sileo on our device.
(Ver.2.10)

**Comment by sabogalc** [comment]
Same problem here, iPhone 6S iOS 14.5
![20210430_000550](https://user-images.githubusercontent.com/53708281/116647279-23e6cd80-a948-11eb-99e0-5acc1d75fc4f.jpg)

**Comment by raspberryenvoie** [comment]
Odysseyra1n has been updated to fix this issue. I'll update odysseyn1x soon

**Comment by raspberryenvoie** [comment]
I've just published the [new release](https://github.com/raspberryenvoie/odysseyn1x/releases) that fixes this issue!

**Comment by duumxh** [comment]
There's no ISO's in latest release

**Comment by sabogalc** [comment]
How do we build an ISO from the source code?

**Comment by raspberryenvoie** [comment]
> There's no ISO's in latest release

Sorry, I forgot the ISOs. It's fixed now!

**Comment by raspberryenvoie** [comment]
> How do we build an ISO from the source code?

Check the README.md file

**Comment by sabogalc** [comment]
> > How do we build an ISO from the source code?
> 
> Check the README.md file

I see that it has to be in a Debian based system. Would WSL 2 work or would I need to boot into Linux to build it?

**Comment by raspberryenvoie** [comment]
I've never used WSL. Does it have apt?

**Comment by duumxh** [comment]
I've successfully built it using wsl2 (Debian from Microsoft Store)
![image](https://user-images.githubusercontent.com/36641860/116711210-7abfc780-a987-11eb-98f9-4b270e6c1808.png)
