### ISSUE TITLE
Odysseyra1n doesn't want to be installed on 14.4.2 device

### ISSUE THREAD

**Issue by HelloKS** [raspberryenvoie/odysseyn1x#25]
I'm using iPad Pro 10.5 (2nd Gen) on iOS 14.4.2, jailbroken with odysseyn1x 2.11 + checkra1n.
![error](https://user-images.githubusercontent.com/3853894/116725559-00da1d80-aa1d-11eb-8b7a-1c9fe0497571.jpg)

**Comment by raspberryenvoie** [comment]
Does this error occur using a different odysseyn1x version? Have you ever been able to install odysseyn1x on your iPad Pro?

**Comment by HelloKS** [comment]
Fast review: it looks like script wants to determine ios major version by omiting last dot, but as 14.4.2 contains two dots it fails and resolves as 14.4 instead of 14. Most likely upstream has same issue on 14.4.2.

**Comment by HelloKS** [comment]
> 
> 
> Does this error occur using a different odysseyn1x version? Have you ever been able to install odysseyn1x on your iPad Pro?

I used odysseyra1n on same device with ios 14.4 previously, it worked.

**Comment by raspberryenvoie** [comment]
That's what I was thinking after looking at the problematic lines (shown by the error message) of `odyssey-device-deploy.sh` created by the odysseyra1n script

**Comment by HelloKS** [comment]
I think this is related to upstream script. Should I move this issue to upstream or leave this in here? I'm not sure..

**Comment by raspberryenvoie** [comment]
You're right it's related to the upstream script.
I made a PR on the repo to fix that.

**Comment by aczw** [comment]
hey, I'm relatively new to all this but it seems like your PR was merged around 2 hours ago (https://github.com/coolstar/Odyssey-bootstrap/pull/22), but the script is still failing for me on v2.11. I'm using an iPhone 7 on 14.4.2. I feel like I'm missing something...

**Comment by raspberryenvoie** [comment]
I was waiting for my PR to be merged before releasing a fix

**Comment by raspberryenvoie** [comment]
Fixed in the [latest release](https://github.com/raspberryenvoie/odysseyn1x/releases)!
