### ISSUE TITLE
Windows crashes to blue screen

### ISSUE THREAD

**Issue by anthony6116** [raspberryenvoie/odysseyn1x#26]
Whenever i try to install the iso to my flash drive with balena etcher right after the validating part my windows 10 pc crashes to the blue screen every time.

**Comment by raspberryenvoie** [comment]
Perhaps it's an issue with your usb flash drive or with balenaEtcher. You can also try to flash the usb drive with Rufus and make sure to select "DD mode" and GPT

**Comment by anthony6116** [comment]
Yeah it’s some problem with balena etcher since i tried many different iso’s and all crashed but yeah rufus worked just fine so all is good now.

**Comment by raspberryenvoie** [comment]
Good news! I'm closing this issue
