### ISSUE TITLE
After install odysseyra1n, unable to install project sandcastle

### ISSUE THREAD

**Issue by fhc5326** [raspberryenvoie/odysseyn1x#28]
After I install odysseyra1n, I want to install project sandcastle, and I choose odysseyra1n, but it told me can't connect.
what should I do?

BTW, I unable to start project sandcastle becasue it told me Failed to transfer image to devices, what should I do?

Devices:iPod Touch 7Gen
iOS Version:14.5.1

**Comment by raspberryenvoie** [comment]
Can you send a photo of the error message please?

**Comment by aczw** [comment]
![IMG_0245](https://user-images.githubusercontent.com/79176651/117520912-e94ce880-af78-11eb-944b-379f0e90899c.jpg)
(I had to use the shell for _reasons_ but I pretty much just followed your script)

device: iPhone 7
iOS: 14.1

I'm using checkra1n and I'm getting the same "Failed to transfer image to device" issue

**Comment by raspberryenvoie** [comment]
Does it work with older versions of checkra1n? Or older odysseyn1x builds

**Comment by aczw** [comment]
I don't have access to macOS/Linux so the checkra1n version is tied down to the Odysseyn1x version, but these were my results:

v2.7 (checkra1n 0.12.0): pongoOS did not recognize the command `fdt`, if I remember correctly they removed it in this version, so nothing you and I can do there

v2.8 (checkra1n 0.12.1): same issue as with v2.7, pongoOS returns `Bad command: fdt`

v2.9 (checkra1n 0.12.2): same issue as with v2.7 and v2.8, pongoOS returns `Bad command: fdt`

v2.10/v2.11/v2.11.1 should have the same checkra1n/pongoOS versions and my comment above was the result of that. The good news is that on checkra1n 0.12.3 they added back the `fdt` command. The bad news is that it still doesn't work :)

Here's a pic for good measure:
![IMG_0252](https://user-images.githubusercontent.com/79176651/117546590-2789ec80-aff9-11eb-8ef0-52d71aec2a00.jpg)

**Comment by raspberryenvoie** [comment]
Thank you! I don't have a good knowledge of pongoOS but I saw that the `fdt` was used in `load-linux.c`. If this command doesn't work, then there's nothing we can do.
Out of curiosity: How did you discover that this was the problem?

**Comment by aczw** [comment]
If you're talking about the `fdt` command being removed, this is not the first time I've tried installing Project Sandcastle, far from it ;-; I've encountered this issue in the past, you can see [here](https://github.com/checkra1n/pongoOS/issues/33) where I was proven wrong about it!

In terms of the `fdt` command not working, I have no idea. Maybe Project Sandcastle isn't using it correctly anymore, maybe something changed in pongoOS that's caused it to stop functioning, personally I dunno.

Either way, I swear to god I've been trying to get Project Sandcastle to work for like the past 3 months... I've even created a Ubuntu partition on my PC and built the `load-linux.c` file myself, still nada. I hate everything about this, I just wanna play around with Android on my iPhone :(

**Comment by raspberryenvoie** [comment]
I see. I remember I was able to install Android on my iPhone running iOS 13. Unfortunately Project Sandcastle hasn't been updated since a year... I hope this issue will be fixed.
As we can't do anything, I might close this issue

**Comment by thxrben** [comment]
Hi yall, 
I started debugging this issue for myself. Running iPhone 7 with iOS 15 something on it.

The firmware wont load behind 1048576 bytes, so nothing behind 2^20 is being uploaded.
I have some ideas why this is the case, e.g. integer limits or more.
I have to take a look what exactly happens and why this is the case, but this seems most likely.

**Comment by aczw** [comment]
please keep us updated!!

**Comment by thxrben** [comment]
This wont be an easy fix, mainly cause I cannot say what exactly goes wrong yet.
It doesnt seem to be to the upload-script itself, but rather pongoOS. 
Got to read further into it :)

EDIT: And btw: Do not use a USB-C -> Lighting Cable. For me, only running through a regular USB Hub was working.
