### ISSUE TITLE
Make New Build for A7

### ISSUE THREAD

**Issue by CanerKaraca23** [raspberryenvoie/odysseyn1x#29]
Can you make a new build for checkra1n 0.10.1? Last build was v2.4. A7 devices only jailbreakable on 0.10.1. Thanks.

**Comment by raspberryenvoie** [comment]
Okay I'll do that tomorrow, when I'll update odysseyn1x for checkra1n 0.12.4 beta. I'll release a checkra1n 0.10.1 version too.

**Comment by CanerKaraca23** [comment]
Thanks.

**Comment by raspberryenvoie** [comment]
I've just released it. Download it [here](https://github.com/raspberryenvoie/odysseyn1x/releases/tag/v2.12-checkra1n-0.10.1) :)
