### ISSUE TITLE
“Setup Android Sandcastle” SSH returns “Access Denied“

### ISSUE THREAD

**Issue by ghost** [raspberryenvoie/odysseyn1x#3]
When I click “Setup Android Sandcastle,” it tries to SSH to root@127.0.0.1 and even with the correct password (I changed the default root password), it doesn’t work. It just says “Access denied, try again.”

**Comment by raspberryenvoie** [comment]
Hi,
Do you have OpenSSH installed?

**Comment by ghost** [comment]
Yeah. I installed it with OdysseyRa1n and then after that I reinstalled it just to be sure.

**Comment by raspberryenvoie** [comment]
Okay, I’ll fix it. It doesn’t work because odysseyn1x is configured to connect through SSH using the port 44 (checkra1n enables SSH throught this port) but odysseyra1n uses the 22 port.

**Comment by ghost** [comment]
Oh ok. Thanks!

**Comment by raspberryenvoie** [comment]
Should be fixed in the latest release! https://github.com/raspberryenvoie/odysseyn1x/releases

**Comment by ghost** [comment]
Thanks!
