### ISSUE TITLE
[Question] Is odysseyra1n compatible with iOS 12.5.3?

### ISSUE THREAD

**Issue by sabogalc** [raspberryenvoie/odysseyn1x#31]
I am on odysseyn1x 2.11.1, and I was able to install checkra1n on my iPad Touch 6 with no issues (iOS 12.5.3), but when I tried to run the odysseyra1n script, I received this error.
![16216144019358052142934876178797](https://user-images.githubusercontent.com/53708281/119169333-deda2680-ba2f-11eb-87c5-3443c8336a02.jpg)
Is odysseyra1n not compatible with older iOS versions? Or should I update to a newer version of odysseyn1x?

**Comment by raspberryenvoie** [comment]
You should unplug and replug the cable that connects your iPad to the PC. It should now work :)

It's also recommended to use the latest odysseyn1x version because odysseyra1n has been updated since odysseyn1x v2.11.

**Comment by sabogalc** [comment]
That did the trick, thank you!

**Comment by raspberryenvoie** [comment]
You're welcome :)
