### ISSUE TITLE
Checkra1n stuck at Checking if Device is ready

### ISSUE THREAD

**Issue by Frischkase** [raspberryenvoie/odysseyn1x#34]
When I try to jailbreak my Iphone 8 plus checkra1n is just stuck on Checking if Device is ready.

iDevice: IPhone 8 pls
IOS: IOS 14.6

Yes Skip A11 BPR check was on.
And passcode was removed too.

**Comment by deontw** [comment]
Well, I do not think that is Odysseyn1x's fault. You could try to use shell to jailbreak your device.

checkra1n -c

**Comment by Frischkase** [comment]
I already tried to use cli mode but it doesn't work too.

**Comment by raspberryenvoie** [comment]
Have you ever been able to jailbreak your iPhone 8 Plus? I don't think it's odysseyn1x's fault, it might be your PC, your cable or your USB port (you can try a different one)

**Comment by Frischkase** [comment]
Yea I think imma just close the issue because I started to think checkra1n itself has problems with my pc
