### ISSUE TITLE
[QUESTION] Can I run odysseyn1x on arm hardware (not amd)

### ISSUE THREAD

**Issue by loyahdev** [raspberryenvoie/odysseyn1x#39]
I have just wanted to see if this is possible

**Comment by raspberryenvoie** [comment]
No, it won't work. What do you want to run it on?

**Comment by loyahdev** [comment]
> No, it won't work. What do you want to run it on?

An m1 Mac if I can’t no buggy but yeah

**Comment by raspberryenvoie** [comment]
Yeah it won't work
