### ISSUE TITLE
ssh and terminal gets broken everytime A11 device

### ISSUE THREAD

**Issue by cs59** [raspberryenvoie/odysseyn1x#41]
So I have a device iPhone 8 Plus, and only having one problem with ssh and terminal, 
Whenever I install odysseyra1n on my device and then open sileo and update all packages and install libhooker then restart my ios then rejb again and then when i install Newterm 2 and open it then it shows me the error as u can see i attached it in the image above, and yes also Mterminal not work either, even I tried to install openssh package from sileo then tried to ssh my device with windows 11, linux mint and even macos but these all gives me same error as soon as I try to connect my device then it instantly refuses the connection, also, I tried to future restore my device to 14.4 and setup as new and tried to install odysseyra1n and after installing the error still persists, I even again future restore my device to 14.8 using shsh blobs and installed odysseyra1n but same i can't able to use newterm or any other terminal nor can't ssh my device, seriously very very strange error i ever got, hope u guyz can help me
![J4YEbu8p](https://user-images.githubusercontent.com/68501788/183297186-25a718ed-6365-4530-9a4d-82ab76c60d6b.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/68501788/183297190-af8506fa-3f14-4212-b113-e13432bb1426.png)
EDIT: If i directly install cydia from checkra1n loader app then all works fine, i able to ssh my device and use terminal, but only not work if i install odysseyra1n

**Comment by raspberryenvoie** [comment]
Hi, from what you said, it's probably an issue with odysseyra1n. It would be best to report it to the odysseyra1n repo

**Comment by cs59** [comment]
> Hi, from what you said, it's probably an issue with odysseyra1n. It would be best to report it to the odysseyra1n repo

Ok, can u give me the link where can I report this issue? I tried to find but can’t, also in Reddit no one reply me

**Comment by raspberryenvoie** [comment]
[Here](https://github.com/coolstar/Odyssey-bootstrap) it is!
