### ISSUE TITLE
can i help translate this?

### ISSUE THREAD

**Issue by olivertzeng** [raspberryenvoie/odysseyn1x#43]

**Comment by raspberryenvoie** [comment]
Hi! Thanks for wanting to support this project! What part of the project would you like to translate and into which language? Translating the  whole program would require quite some work. Perhaps translating the README.MD would be enough?

**Comment by raspberryenvoie** [comment]
Hi! Thanks for wanting to support this project! Which part of the project would you like to translate and into which language? Translating the  whole program would require quite some work. Perhaps translating the README.MD would be enough?

**Comment by olivertzeng** [comment]
I would like to translate the WHOLE text including the UI, except README no matter how much work. I want to translate it to Traditional Chinese (zh_TW)

**Comment by olivertzeng** [comment]
Oh yeah ive submittied your work to distrowatch.com

**Comment by raspberryenvoie** [comment]
Why not, if you think this can help a lot of people. Just out of curiosity, is your motivation for translating it into Traditional Chinese personal or do you know people wanting to use odysseyn1x in Chinese?
Do you know if additional packages are required to output Chinese characters?

**Comment by raspberryenvoie** [comment]
You submitted odysseyn1x to distrowatch which means that odusseyn1x can be tested on the website, right?

**Comment by olivertzeng** [comment]
> Why not, if you think this can help a lot of people. Just out of curiosity, is your motivation for translating it into Traditional Chinese personal or do you know people wanting to use odysseyn1x in Chinese? Do you know if additional packages are required to output Chinese characters?

oh its just personal

**Comment by olivertzeng** [comment]
> You submitted odysseyn1x to distrowatch which means that odusseyn1x can be tested on the website, right?

the request haven't been replied yet so no ig

**Comment by olivertzeng** [comment]
> Why not, if you think this can help a lot of people. Just out of curiosity, is your motivation for translating it into Traditional Chinese personal or do you know people wanting to use odysseyn1x in Chinese? Do you know if additional packages are required to output Chinese characters?

wait is there some sort of local directory or sth like LC_STRINGS etc... 
or do I have to create a branch to directly modify the main file?

**Comment by olivertzeng** [comment]
@raspberryenvoie

**Comment by olivertzeng** [comment]
> Why not, if you think this can help a lot of people. Just out of curiosity, is your motivation for translating it into Traditional Chinese personal or do you know people wanting to use odysseyn1x in Chinese? Do you know if additional packages are required to output Chinese characters?

additional packages: fonts that support zh_TW
would actually suggest the taipei-sans-tc font https://sites.google.com/

**Comment by olivertzeng** [comment]
I;m a taiwanese btw

**Comment by raspberryenvoie** [comment]
Hi @olivertzeng. I'm sorry for answering so late.
Could you explain what LC_STRINGS are?

**Comment by olivertzeng** [comment]
LoCalizeable STRINGS ig @raspberryenvoie

**Comment by BAS27-BKK** [comment]
> No description provided.

**Comment by raspberryenvoie** [comment]
I'm sorry I don't think I'm going to port this feature due to a lack of personal time. However if you are able to develop it, don't hesitate to open a pull request.

**Comment by olivertzeng** [comment]
ok
