### ISSUE TITLE
7p 10.2.1 Meridian-v0.9-007

### ISSUE THREAD

**Issue by BAS27-BKK** [raspberryenvoie/odysseyn1x#46]
7p 10.2.1 Meridian-v0.9-007
1.after jailbreaked reboot
2.cydia missing
3.shh command:rm /.meridian_installed ,it told me "-sh: rm: command not found"
ssh
4.I tried Meridian-pb1 Meridian-pb2 Meridian-pb3 Meridian-pb4 Meridian-pb5 Meridian-v0.9-001 -Meridian-v0.9-007
but, it didn't work
5.I found yalu102-beta7-always-install-cydia.ipa, just that way always-install-cydia,pls help.

_Originally posted by @JohonsonCydia in https://github.com/PsychoTea/MeridianJB/issues/51_

_Originally posted by @BAS27-BKK in https://github.com/BAS27-BK/Chatree-Putaek/issues/2_

**Comment by BAS27-BKK** [comment]
> 7p 10.2.1 Meridian-v0.9-007
> 
> 1.after jailbreaked reboot
> 
> 2.cydia missing
> 
> 3.shh command:rm /.meridian_installed ,it told me "-sh: rm: command not found"
> 
> ssh
> 
> 4.I tried Meridian-pb1 Meridian-pb2 Meridian-pb3 Meridian-pb4 Meridian-pb5 Meridian-v0.9-001 -Meridian-v0.9-007
> 
> but, it didn't work
> 
> 5.I found yalu102-beta7-always-install-cydia.ipa, just that way always-install-cydia,pls help.
> 
> _Originally posted by @JohonsonCydia in https://github.com/PsychoTea/MeridianJB/issues/51_
> 
> _Originally posted by @BAS27-BKK in https://github.com/BAS27-BK/Chatree-Putaek/issues/2_

**Comment by raspberryenvoie** [comment]
I think you opened an issue at the wrong place.
