### ISSUE TITLE
AMD CPUs support

### ISSUE THREAD

**Issue by Void48** [raspberryenvoie/odysseyn1x#47]
Hey :) I recently tried the [WinRa1n](https://onejailbreak.com/blog/winra1n-jailbreak/) tool and managed to successfully jailbreak my iPhone with a 5000 series AMD Ryzen CPU which surprised me. Jailbreaking my iDevice **_never_** worked for me with odysseyn1x or the regular checkra1n release so I wanted to ask if you could look into implementing AMD support now that we know it's possible

**Comment by raspberryenvoie** [comment]
Normally this should work for AMD CPUs as well. I will unfortunately not look further into this.
