### ISSUE TITLE
can't boot [Firmware Bug]: TSC_DEADLINE

### ISSUE THREAD

**Issue by weijen6** [raspberryenvoie/odysseyn1x#6]
i can't boot
how can i fix it?
thank you very much

[Firmware Bug]: TSC_DEADLINE

I7 4790K
ASUS Z87 GRYPHON

**Comment by raspberryenvoie** [comment]
Hey what's the full error written on your screen?

**Comment by raspberryenvoie** [comment]
Also updating your BIOS could fix it.

**Comment by MyCatCondo** [comment]
https://www.asus.com/us/Motherboards/GRYPHON_Z87/HelpDesk_BIOS/

**Comment by ghost** [comment]
> Also updating your BIOS could fix it.

https://www.asus.com/us/Motherboards/GRYPHON_Z87/HelpDesk_BIOS/

**Comment by weijen6** [comment]
Thanks for the help, but the BIOS was originally the latest 2103

**Comment by raspberryenvoie** [comment]
Try again the latest release and use Etcher to burn the USB, otherwise I don't know how I can help you, sorry. I can only tell you to use another computer.

Let me know if you find a workaround :)

**Comment by ghost** [comment]
There have been many releases since then and there might be a fix, so you might want to try again @weijen6

**Comment by ghost** [comment]
Any update?

**Comment by weijen6** [comment]
Thank you very much, I am using the latest version 2.8 and it can be used successfully.
