### ISSUE TITLE
checkra1n 0.10.1 support

### ISSUE THREAD

**Issue by CanerKaraca23** [raspberryenvoie/odysseyn1x#7]
iPhone 5s devices can't jailbreak on 0.10.2, can you add 0.10.1 option?

**Comment by raspberryenvoie** [comment]
There's already what you're looking for, but it doesn't support project sandcastle:
https://github.com/raspberryenvoie/odysseyn1x/releases/tag/v0.10.1

**Comment by CanerKaraca23** [comment]
Yes, it doesn't includes fixes also. We want new build for this :(

**Comment by raspberryenvoie** [comment]
This build ships with checkra1n 0.10.1, what's wrong?
To successfully jailbreak A7 devices, follow this video: https://www.youtube.com/watch?v=w1FvF_cWt3A

**Comment by raspberryenvoie** [comment]
You would like a build with project sancastle for A7 devices too, right?

**Comment by raspberryenvoie** [comment]
This build ships with checkra1n 0.10.1, what's wrong?
To successfully jailbreak A7 devices, follow this video: https://www.youtube.com/watch?v=w1FvF_cWt3A

If I understood, you want the build to be updated?

**Comment by CanerKaraca23** [comment]
Yes, I want a build updated for checkra1n 0.10.1. Or add option for checkra1n 0.10.1 to load menu of latest odysseyn1x.

**Comment by raspberryenvoie** [comment]
Ok, I'll do it in the next days

**Comment by raspberryenvoie** [comment]
What you're looking for is available here :)
https://github.com/raspberryenvoie/odysseyn1x/releases/tag/v2.4-checkra1n-0.10.1
