### ISSUE TITLE
Checkra1n 0.11.0 support

### ISSUE THREAD

**Issue by DrazzyXD** [raspberryenvoie/odysseyn1x#8]
Can you please update the checkra1n file to version 0.11.0?

**Comment by raspberryenvoie** [comment]
Done in https://github.com/raspberryenvoie/odysseyn1x/commit/e2d65056005096df3c8000d4175c45e269250f4b. I'm releasing the iso soon!

**Comment by TempAccountNull** [comment]
@raspberryenvoie Here: All I changed was the PR and set version to 2.5. Compiled and ready to go! 
Link to iso: https://mega.nz/file/Sd1RXQTJ#Hxe_xCWh87PrDNvljwIUm36ENQatQXJv9UKmtJdQr40

Images:
![CR](https://user-images.githubusercontent.com/11286901/93866250-0accbe80-fc8d-11ea-83ef-fffbb1683f2d.PNG)
![LOG](https://user-images.githubusercontent.com/11286901/93866262-0d2f1880-fc8d-11ea-8ca3-9f69644b44e9.PNG)

**Comment by raspberryenvoie** [comment]
Oh that's nice from you! I've just released v2.5. You can download it [here](https://github.com/raspberryenvoie/odysseyn1x/releases/tag/v2.5).
Have a beautiful day :)
